ZOOKEEPER-3790: zkpython: Define HAVE_OPENSSL_H, as the extension uses it
The flag is unconditionally defined for now, as the function is
unconditionally called.

    src/c/zookeeper.c:646:10: warning: implicit declaration of function 'zookeeper_init_ssl'; did you mean 'zookeeper_init2'? [-Wimplicit-function-declaration]
         zh = zookeeper_init_ssl( host, cert_str, watcherfn != Py_None ? watcher_dispatch : NULL,

              ^~~~~~~~~~~~~~~~~~
              zookeeper_init2