[ZOOKEEPER-4641] GH CI fails with 'error: implicit declaration of function ‘FIPS_mode’ [-Werror=implicit-function-declaration]'
Modifications:
- remove the block, as it is used only for debug