ZOOKEEPER-4327: RequestThrottlerTest: Only resume after looking at metrics
Resuming the pipeline before looking at the metrics triggers a race
between the test and other server threads, causing us to sometimes
observe a larger "prep_processor_request_queued" than expected.

The corresponding failures look like this:

    RequestThrottlerTest.testGlobalOutstandingRequestThrottlingWithRequestThrottlerDisabled:340 expected: <3> but was: <7>

The metric we look at is updated at the front of the pipeline, before
the portion blocked by 'resumeProcess'; we don't have to wait for the
latter to observe the effect of the global outstanding limit.