ZOOKEEPER-3624: Fix flaky `QuorumPeerMainTest::testFailedTxnAsPartOfQuorumLoss`
```
org.opentest4j.AssertionFailedError: create /zk2 should have failed
	at org.apache.zookeeper.server.quorum.QuorumPeerMainTest.testFailedTxnAsPartOfQuorumLoss(QuorumPeerMainTest.java:762)
```

The test starts other members before the `create` operation. This causes
the old leader rejoin with them to form quorum.

This pr moves starting of stopped members after `create`.