ZOOKEEPER-3790: zkpython: Defined THREADED, as the sync API is used
Without this, compilation produces a number of warnings about
undefined functions (and misleading suggestions!) as it only sees the
async API:

    src/c/zookeeper.c:1080:13: warning: implicit declaration of function 'zoo_delete'; did you mean 'zoo_adelete'? [-Wimplicit-function-declaration]
       int err = zoo_delete(zh, path, version);
                 ^~~~~~~~~~
                 zoo_adelete