ZOOKEEPER-3790: zkpython compilation and testing issues
This series makes the zkpython "contrib" compile cleanly, and makes the tests runnable out of the box with Python 3:

  * Defined `THREADED`, as zkpython uses the sync API

    Without this, compilation produces a number of warnings about undefined functions (and misleading suggestions!) as it only sees the async API:

        src/c/zookeeper.c:1080:13: warning: implicit declaration of function 'zoo_delete'; did you mean 'zoo_adelete'? [-Wimplicit-function-declaration]
           int err = zoo_delete(zh, path, version);
                     ^~~~~~~~~~
                     zoo_adelete

  * Define `HAVE_OPENSSL_H`, as the extension calls zookeeper_init_ssl

    The flag is unconditionally defined for now, as the function is unconditionally called.

        src/c/zookeeper.c:646:10: warning: implicit declaration of function 'zookeeper_init_ssl'; did you mean 'zookeeper_init2'? [-Wimplicit-function-declaration]
             zh = zookeeper_init_ssl( host, cert_str, watcherfn != Py_None ? watcher_dispatch : NULL,

                  ^~~~~~~~~~~~~~~~~~
                  zookeeper_init2

  * Make SSL support optional (but on by default)

  * Raise `MemoryError` if module initialization fails

  * Allow for version/ABI information in shared object name

    In some versions of the Python framework, native extensions encode the interpreter version and some ABI information in the filename, giving e.g. `zookeeper.cpython-37m-x86_64-linux-gnu.so` instead of `zookeeper.so`.  Take this into account when setting up test runs.

  * Make sure test failures are detected

  * `async` is a keyword in Python 3.5+

Author: Damien Diederen <dd@crosstwine.com>

Reviewers: Mate Szalay-Beko <szalay.beko.mate@gmail.com>, Norbert Kalmar <nkalmar@apache.org>

Closes #1312 from ztzg/ZOOKEEPER-3790-zkpython-compilation-and-testing-issues